name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
         # browser: chrome
          # headless: true
          # spec: cypress/e2e/integration/25-Project02Demo.cy.js
           command: npm run test:spesific 
